// <auto-generated />
// This file provides the EF Core migration baseline.
// Run: dotnet ef migrations add InitialCreate --project ServerCat.Infrastructure --startup-project ServerCat.Api
// Then: dotnet ef database update --project ServerCat.Infrastructure --startup-project ServerCat.Api

// NOTE: The actual migration files are generated by EF Core tooling from the DbContext.
// The schema defined in ApplicationDbContext.cs is the source of truth.
// This placeholder documents the setup steps and reminds developers to run migrations.

namespace ServerCat.Infrastructure.Data.Migrations;

// Migration generation command reference:
//
// From solution root:
//   cd backend
//   dotnet ef migrations add InitialCreate \
//     --project ServerCat.Infrastructure \
//     --startup-project ServerCat.Api \
//     --output-dir Data/Migrations
//
//   dotnet ef database update \
//     --project ServerCat.Infrastructure \
//     --startup-project ServerCat.Api
//
// The app auto-applies migrations on startup via:
//   await dbCtx.Database.MigrateAsync();
// (see Program.cs)
